name: prune_llm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - comm=0.1.2=py39h06a4308_0
  - cryptography=41.0.3=py39hdda0065_0
  - cudatoolkit=11.3.1=h9edb442_10
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - exceptiongroup=1.0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.0.0=py39h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.25.0=py39h2f386ee_0
  - ipython=8.15.0=py39h06a4308_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py39h06a4308_1
  - jpeg=9e=h166bdaf_1
  - jupyter_client=8.1.0=py39h06a4308_0
  - jupyter_core=5.3.0=py39h06a4308_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libuv=1.43.0=h7f98852_0
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - nettle=3.6=he412f7d_0
  - numpy=1.24.3=py39h14f4228_0
  - numpy-base=1.24.3=py39h31eccc5_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.11=h7f8727e_2
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.2=py39ha612740_0
  - pip=23.2.1=py39h06a4308_0
  - platformdirs=3.10.0=py39h06a4308_0
  - pooch=1.7.0=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39h06a4308_1
  - pyopenssl=23.2.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch-mutex=1.0=cuda
  - pyzmq=25.1.0=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_0
  - scipy=1.10.1=py39h14f4228_0
  - setuptools=68.0.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.10.1=py39_cu113
  - torchvision=0.11.2=py39_cu113
  - tornado=6.3.3=py39h5eee18b_0
  - traitlets=5.7.1=py39h06a4308_0
  - typing_extensions=4.8.0=pyha770c72_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - accelerate==0.24.1
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - chardet==5.2.0
    - charset-normalizer==3.3.0
    - click==8.1.7
    - colorama==0.4.6
    - contourpy==1.2.0
    - cycler==0.12.1
    - datasets==2.16.1
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - evaluate==0.4.1
    - filelock==3.12.4
    - flash-attn==2.3.6
    - fonttools==4.45.1
    - frozenlist==1.4.0
    - fsspec==2023.9.2
    - gitdb==4.0.10
    - gitpython==3.1.37
    - huggingface-hub==0.20.2
    - importlib-resources==6.1.1
    - jinja2==3.1.2
    - kiwisolver==1.4.5
    - lxml==5.1.0
    - markupsafe==2.1.3
    - matplotlib==3.8.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - networkx==3.2.1
    - ninja==1.11.1.1
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - packaging==23.2
    - pandas==2.1.1
    - pathtools==0.1.2
    - peft==0.6.2
    - plotly==5.18.0
    - portalocker==2.8.2
    - protobuf==4.24.4
    - psutil==5.9.5
    - pyarrow==13.0.0
    - pyarrow-hotfix==0.6
    - pyparsing==3.1.1
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - regex==2023.10.3
    - responses==0.18.0
    - sacrebleu==2.4.0
    - safetensors==0.4.0
    - sentencepiece==0.1.99
    - sentry-sdk==1.31.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.3
    - tokenizers==0.13.3
    - torch==2.1.1
    - tqdm==4.66.1
    - transformers==4.28.0
    - triton==2.1.0
    - tzdata==2023.3
    - urllib3==2.0.6
    - wandb==0.15.12
    - xxhash==3.4.1
    - yarl==1.9.2
prefix: /data/tir/projects/tir4/users/ldery/anaconda3/envs/prune_llm

